def generate_fibonacci(n):
    """
      Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
      By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    """
    fib_sequence = [1, 2]
    a, b = 1, 2
    while True:
        c = a + b
        if c > n:
            break
        fib_sequence.append(c)
        a, b = b, c
    return fib_sequence

def fibo_even_sum(n):
    """
    By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
    """
    fib_sequence = generate_fibonacci(n)
    even_sum = 0
    for num in fib_sequence:
        if num % 2 == 0:
            even_sum += num
    print("Fibonacci sequence:", fib_sequence)
    print("Sum of even numbers:", even_sum)


fibo_even_sum(8)
fibo_even_sum(10)
fibo_even_sum(34)
fibo_even_sum(60)

